// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package me

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use MailFoldersItemChildFoldersItemMessagesDeltaGetResponseable instead.
type MailFoldersItemChildFoldersItemMessagesDeltaResponse struct {
    MailFoldersItemChildFoldersItemMessagesDeltaGetResponse
}
// NewMailFoldersItemChildFoldersItemMessagesDeltaResponse instantiates a new MailFoldersItemChildFoldersItemMessagesDeltaResponse and sets the default values.
func NewMailFoldersItemChildFoldersItemMessagesDeltaResponse()(*MailFoldersItemChildFoldersItemMessagesDeltaResponse) {
    m := &MailFoldersItemChildFoldersItemMessagesDeltaResponse{
        MailFoldersItemChildFoldersItemMessagesDeltaGetResponse: *NewMailFoldersItemChildFoldersItemMessagesDeltaGetResponse(),
    }
    return m
}
// CreateMailFoldersItemChildFoldersItemMessagesDeltaResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateMailFoldersItemChildFoldersItemMessagesDeltaResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewMailFoldersItemChildFoldersItemMessagesDeltaResponse(), nil
}
// Deprecated: This class is obsolete. Use MailFoldersItemChildFoldersItemMessagesDeltaGetResponseable instead.
type MailFoldersItemChildFoldersItemMessagesDeltaResponseable interface {
    MailFoldersItemChildFoldersItemMessagesDeltaGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
