// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package me

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use MessagesDeltaGetResponseable instead.
type MessagesDeltaResponse struct {
    MessagesDeltaGetResponse
}
// NewMessagesDeltaResponse instantiates a new MessagesDeltaResponse and sets the default values.
func NewMessagesDeltaResponse()(*MessagesDeltaResponse) {
    m := &MessagesDeltaResponse{
        MessagesDeltaGetResponse: *NewMessagesDeltaGetResponse(),
    }
    return m
}
// CreateMessagesDeltaResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateMessagesDeltaResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewMessagesDeltaResponse(), nil
}
// Deprecated: This class is obsolete. Use MessagesDeltaGetResponseable instead.
type MessagesDeltaResponseable interface {
    MessagesDeltaGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
